import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "C161fMDP3FL",
    video_title: "Instagram Reel",
    video_description: "Check out this amazing Instagram reel!",
    tags: ["Instagram", "Reel", "Content"],
    cover_image: "C161fMDP3FL",
    publish_date: "2024-01-10",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/C161fMDP3FL/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
    project_images: [],
    category: ["Reels"],
    duration: "2:31",
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: true,
  },
  {
    id: "DVnkX7PgVYK",
    video_title: "Instagram Montage",
    video_description: "Creative montage video showcasing dynamic transitions and storytelling.",
    tags: ["Instagram", "Montage", "Content"],
    cover_image: "DVnkX7PgVYK",
    publish_date: "2024-01-15",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DVnkX7PgVYK/?igsh=MTF5ZnpwY3EzODJ0ag==",
    project_images: [],
    category: ["Montages"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: true,
  },
  {
    id: "DWDhaJAlJkj",
    video_title: "Instagram Montage",
    video_description: "Creative montage video showcasing dynamic transitions and storytelling.",
    tags: ["Instagram", "Montage", "Content"],
    cover_image: "DWDhaJAlJkj",
    publish_date: "2024-01-16",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DWDhaJAlJkj/?igsh=ZjdsaXJrcDh3Nmls",
    project_images: [],
    category: ["Montages"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: true,
  },
  {
    id: "DWRBvNrAg3W",
    video_title: "Instagram Montage",
    video_description: "Creative montage video showcasing dynamic transitions and storytelling.",
    tags: ["Instagram", "Montage", "Content"],
    cover_image: "DWRBvNrAg3W",
    publish_date: "2024-01-17",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DWRBvNrAg3W/?igsh=MWVza2d3bWt4bGJ0Nw==",
    project_images: [],
    category: ["Montages"],

    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: true,
  },
  {
    id: "DCRfYpGvmkv",
    video_title: "Instagram Montage",
    video_description: "Creative montage video showcasing dynamic transitions and storytelling.",
    tags: ["Instagram", "Montage", "Content"],
    cover_image: "DCRfYpGvmkv",
    publish_date: "2024-01-18",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DCRfYpGvmkv/?igsh=c2UycjVvZ3V4MGN5",
    project_images: [],
    category: ["Montages"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: true,
  },
  {
    id: "DVS4Gt3id9p",
    video_title: "Instagram Promotion",
    video_description: "Promotional video content.",
    tags: ["Instagram", "Promotion", "Content"],
    cover_image: "DVS4Gt3id9p",
    publish_date: "2024-01-19",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DVS4Gt3id9p/?igsh=MXhrcjdhb2ZmdG5hYg==",
    project_images: [],
    category: ["Promotions"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: true,
  },
  {
    id: "DVK7dlcCTcU",
    video_title: "Instagram Promotion",
    video_description: "Promotional video content.",
    tags: ["Instagram", "Promotion", "Content"],
    cover_image: "DVK7dlcCTcU",
    publish_date: "2024-01-20",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DVK7dlcCTcU/?igsh=YmI1anV4ajE0eDZl",
    project_images: [],
    category: ["Promotions"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: true,
  },
  {
    id: "DVIQgw5Cfcm",
    video_title: "Instagram Promotion",
    video_description: "Promotional video content.",
    tags: ["Instagram", "Promotion", "Content"],
    cover_image: "DVIQgw5Cfcm",
    publish_date: "2024-01-21",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DVIQgw5Cfcm/?igsh=NXUzZnI0bHlnMWly",
    project_images: [],
    category: ["Promotions"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: true,
  },
  {
    id: "DWJVr1nCaJr",
    video_title: "Instagram Promotion",
    video_description: "Promotional video content.",
    tags: ["Instagram", "Promotion", "Content"],
    cover_image: "DWJVr1nCaJr",
    publish_date: "2024-01-22",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DWJVr1nCaJr/?igsh=MTQxNngyczE5aXc1NQ==",
    project_images: [],
    category: ["Promotions"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: true,
  },
  {
    id: "DVdfeEriVwA",
    video_title: "Instagram Promotion",
    video_description: "Promotional video content.",
    tags: ["Instagram", "Promotion", "Content"],
    cover_image: "DVdfeEriVwA",
    publish_date: "2024-01-23",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DVdfeEriVwA/?igsh=MTl5cGNrNW5nd29seA==",
    project_images: [],
    category: ["Promotions"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: true,
  },
  {
    id: "GDrive_1wmdrOgg",
    video_title: "Promotional Video",
    video_description: "Professional promotional video content.",
    tags: ["Promotion", "Video", "Content"],
    cover_image: "GDrive_1wmdrOgg",
    publish_date: "2024-01-24",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/1wmdrOgg3djl5RDn6GzToKFN7yCDOF7r4/view?usp=drive_link",
    project_images: [],
    category: ["Promotions"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_12NroNYX",
    video_title: "Promotional Video",
    video_description: "Professional promotional video content.",
    tags: ["Promotion", "Video", "Content"],
    cover_image: "GDrive_12NroNYX",
    publish_date: "2024-01-25",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/12NroNYXSlxjvqK0e5zB_PG0SCt6wLsFm/view?usp=drive_link",
    project_images: [],
    category: ["Promotions"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_161Ss9DX",
    video_title: "Promotional Video",
    video_description: "Professional promotional video content.",
    tags: ["Promotion", "Video", "Content"],
    cover_image: "GDrive_161Ss9DX",
    publish_date: "2024-01-26",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/161Ss9DX5J2TK2RYBEeEcPE5cJIumh17Z/view?usp=drive_link",
    project_images: [],
    category: ["Promotions"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_1EEaDEgv",
    video_title: "Promotional Video",
    video_description: "Professional promotional video content.",
    tags: ["Promotion", "Video", "Content"],
    cover_image: "GDrive_1EEaDEgv",
    publish_date: "2024-01-27",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/1EEaDEgvAjwmb4Gy_hFwGaTjcOkpxr_ZY/view?usp=drive_link",
    project_images: [],
    category: ["Promotions"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_1R0KT6Ae",
    video_title: "B-Roll Footage",
    video_description: "Professional B-roll video content for editing.",
    tags: ["B-roll", "Footage", "Content"],
    cover_image: "GDrive_1R0KT6Ae",
    publish_date: "2024-01-28",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/1R0KT6Ae733ozD6fyfPkrg1ZpFFJMSTqe/view?usp=drive_link",
    project_images: [],
    category: ["B-roll"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_1kdyxQFK",
    video_title: "B-Roll Footage",
    video_description: "Professional B-roll video content for editing.",
    tags: ["B-roll", "Footage", "Content"],
    cover_image: "GDrive_1kdyxQFK",
    publish_date: "2024-01-29",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/1kdyxQFKlf4942VHbTcFDGr0iqV24Gcxd/view?usp=drive_link",
    project_images: [],
    category: ["B-roll"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_1Cow95aO",
    video_title: "B-Roll Footage",
    video_description: "Professional B-roll video content for editing.",
    tags: ["B-roll", "Footage", "Content"],
    cover_image: "GDrive_1Cow95aO",
    publish_date: "2024-01-30",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/1Cow95aOJTjnKFMBdogda8Zw_btciyfui/view?usp=drive_link",
    project_images: [],
    category: ["B-roll"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_1JvyF3wv",
    video_title: "B-Roll Footage",
    video_description: "Professional B-roll video content for editing.",
    tags: ["B-roll", "Footage", "Content"],
    cover_image: "GDrive_1JvyF3wv",
    publish_date: "2024-01-31",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/1JvyF3wvXGWhM2ItJFW2s8I5aol9pDoh8/view?usp=drive_link",
    project_images: [],
    category: ["B-roll"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_1fsLvr6q",
    video_title: "Montage Video",
    video_description: "Creative montage video showcasing dynamic transitions and storytelling.",
    tags: ["Montage", "Video", "Content"],
    cover_image: "GDrive_1fsLvr6q",
    publish_date: "2024-02-01",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/1fsLvr6qcCNsMg8iObm0WRb24fwe5QnTs/view?usp=drive_link",
    project_images: [],
    category: ["Montages"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_14QnNFMF",
    video_title: "Montage Video",
    video_description: "Creative montage video showcasing dynamic transitions and storytelling.",
    tags: ["Montage", "Video", "Content"],
    cover_image: "GDrive_14QnNFMF",
    publish_date: "2024-02-02",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/14QnNFMFVkarm1AL1sb8t82SOjP1N4buk/view?usp=drive_link",
    project_images: [],
    category: ["Montages"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_11BzC8H3",
    video_title: "Montage Video",
    video_description: "Creative montage video showcasing dynamic transitions and storytelling.",
    tags: ["Montage", "Video", "Content"],
    cover_image: "GDrive_11BzC8H3",
    publish_date: "2024-02-03",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/11BzC8H30YZ3oCQYNt1u7lg33bfZuZGys/view?usp=drive_link",
    project_images: [],
    category: ["Montages"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_1E_ptyJY",
    video_title: "Promotional Video",
    video_description: "Professional promotional video content.",
    tags: ["Promotion", "Video", "Content"],
    cover_image: "GDrive_1E_ptyJY",
    publish_date: "2024-02-04",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/1E_ptyJYwzIVhbbGmVRLZfKs3M7rYiDmB/view?usp=drive_link",
    project_images: [],
    category: ["Promotions"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_1Qdc2AqqI",
    video_title: "Advertisement Video",
    video_description: "Professional advertisement video content.",
    tags: ["Advertisement", "Video", "Content"],
    cover_image: "GDrive_1Qdc2AqqI",
    publish_date: "2024-02-05",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/1Qdc2AqqIbkB6sdEZxUpZeQxTW9H6EmpX/view?usp=drive_link",
    project_images: [],
    category: ["Advertisement"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_1lygesHdM",
    video_title: "Advertisement Video",
    video_description: "Professional advertisement video content.",
    tags: ["Advertisement", "Video", "Content"],
    cover_image: "GDrive_1lygesHdM",
    publish_date: "2024-02-06",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/1lygesHdMRspaP8Jo19isT5qJDNCAaE69/view?usp=drive_link",
    project_images: [],
    category: ["Advertisement"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_1aRi-ssJU",
    video_title: "Reel",
    video_description: "Professional reel video content.",
    tags: ["Reel", "Video", "Content"],
    cover_image: "GDrive_1aRi-ssJU",
    publish_date: "2024-02-07",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/1aRi-ssJUqVutxvfu3vGr1UR4pYs1pp-w/view?usp=drive_link",
    project_images: [],
    category: ["Reels"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_1dygM6a4G",
    video_title: "Advertisement Video",
    video_description: "Professional advertisement video content.",
    tags: ["Advertisement", "Video", "Content"],
    cover_image: "GDrive_1dygM6a4G",
    publish_date: "2024-02-08",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/1dygM6a4GGADMQSsiZjG4q570FegJmDV_/view?usp=drive_link",
    project_images: [],
    category: ["Advertisement"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_12a0Xm7Z",
    video_title: "Advertisement Video",
    video_description: "Professional advertisement video content.",
    tags: ["Advertisement", "Video", "Content"],
    cover_image: "GDrive_12a0Xm7Z",
    publish_date: "2024-02-09",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/12a0Xm7Z8uWsJyh7LoTeEqWKDGC2TzheK/view?usp=drive_link",
    project_images: [],
    category: ["Advertisement"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
  {
    id: "GDrive_1gc-h9WMa",
    video_title: "Promotional Video",
    video_description: "Professional promotional video content.",
    tags: ["Promotion", "Video", "Content"],
    cover_image: "GDrive_1gc-h9WMa",
    publish_date: "2024-02-10",
    client_name: "Your Brand",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://drive.google.com/file/d/1gc-h9WMai3X1Da0c_lmkYFEtxzBXJHTM/view?usp=drive_link",
    project_images: [],
    category: ["Promotions"],
    software_used: ["Premiere Pro", "CapCut"],
    is_instagram_reel: false,
    is_google_drive: true,
  },
];
